trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  GOOS:   'windows' # OS to build binaries for
  GOROOT: '/usr/local/go1.11' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/Microsoft/hcsshim' # Path to the module's code $(build.repository.name)
  package: 'github.com/Microsoft/hcsshim/cmd/runhcs' # Go package to build

steps:

- script: |
    mkdir -p '$(modulePath)'
    shopt -s extglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
    echo '##vso[build.updatebuildnumber]GUESS WHAT 6.3 VER'
  displayName: 'Set up the Go workspace'

- script: |
    go get -v -d ./...
    go build -v $(package)
  displayName: 'Get dependencies, then build'

- script: |
    mv runhcs.exe $(Build.ArtifactStagingDirectory)
  displayName: 'Move artifacts to staging directory'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'runhcs'
    targetPath: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Publish artifacts'