/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type AttachmentType string

// List of AttachmentType
const (
	AttachmentTypeVIRTUAL_DISK AttachmentType = "VirtualDisk"
	AttachmentTypeISO AttachmentType = "Iso"
	AttachmentTypePASS_THRU AttachmentType = "PassThru"
)
