/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type Attachment struct {
	Type_ *AttachmentType `json:"Type,omitempty"`
	Path string `json:"Path,omitempty"`
	CachingMode *CachingMode `json:"CachingMode,omitempty"`
	ReadOnly bool `json:"ReadOnly,omitempty"`
	SupportCompressedVolumes bool `json:"SupportCompressedVolumes,omitempty"`
	AlwaysAllowSparseFiles bool `json:"AlwaysAllowSparseFiles,omitempty"`
	SupportEncryptedFiles bool `json:"SupportEncryptedFiles,omitempty"`
}
