/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type CachingMode string

// List of CachingMode
const (
	CachingModeUNCACHED CachingMode = "Uncached"
	CachingModeCACHED CachingMode = "Cached"
	CachingModeREAD_ONLY_CACHED CachingMode = "ReadOnlyCached"
)
