/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type CacheMode string

// List of CacheMode
const (
	CacheModeEMPTY CacheMode = ""
	CacheModeDISABLED CacheMode = "Disabled"
	CacheModeENABLED CacheMode = "Enabled"
	CacheModePRIVATE CacheMode = "Private"
	CacheModePRIVATE_ALLOW_SHARING CacheMode = "PrivateAllowSharing"
)
