/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type Chipset struct {
	Uefi *Uefi `json:"Uefi,omitempty"`
	IsNumLockDisabled bool `json:"IsNumLockDisabled,omitempty"`
	BaseBoardSerialNumber string `json:"BaseBoardSerialNumber,omitempty"`
	ChassisSerialNumber string `json:"ChassisSerialNumber,omitempty"`
	ChassisAssetTag string `json:"ChassisAssetTag,omitempty"`
	EnableHibernation bool `json:"EnableHibernation,omitempty"`
	UseUtc bool `json:"UseUtc,omitempty"`
	LinuxKernelDirect *LinuxKernelDirect `json:"LinuxKernelDirect,omitempty"`
}
