/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

// An object consisting of basic system properties for a compute system
type ComputeSystemProperties struct {
	Id string `json:"Id,omitempty"`
	Name string `json:"Name,omitempty"`
	SystemType *SystemType `json:"SystemType,omitempty"`
	State *State `json:"State,omitempty"`
	Owner string `json:"Owner,omitempty"`
	RuntimeId string `json:"RuntimeId,omitempty"`
	RuntimeOsType *OsType `json:"RuntimeOsType,omitempty"`
	HostingSystemId string `json:"HostingSystemId,omitempty"`
	IsDummy bool `json:"IsDummy,omitempty"`
	ObRoot string `json:"ObRoot,omitempty"`
	RuntimeTemplateId string `json:"RuntimeTemplateId,omitempty"`
}
