/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

// Describes memory configuration for a container.
type ContainerMemory struct {
	// Specifies the memory size in megabytes.
	SizeInMB int32 `json:"SizeInMB,omitempty"`
}
