/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

// Object describing a request to remove a running Container Credential Guard Instance.
type ContainerCredentialGuardRemoveInstanceRequest struct {
	// Globally unique identifier of a running Container Credential Guard Instance.
	Id string `json:"Id,omitempty"`
}
