/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type ContainerCredentialGuardModifyOperation string

// List of ContainerCredentialGuardModifyOperation
const (
	ContainerCredentialGuardModifyOperationADD_INSTANCE ContainerCredentialGuardModifyOperation = "AddInstance"
	ContainerCredentialGuardModifyOperationREMOVE_INSTANCE ContainerCredentialGuardModifyOperation = "RemoveInstance"
)
