/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

// Describes the HvSocket configuration and options for a container.
type ContainerHvSocket struct {
	Config *HvSocketSystemConfig `json:"Config,omitempty"`
	// When true, enables Powershell Direct service in the guest to allow it to use the HvSocket transport.
	EnablePowerShellDirect bool `json:"EnablePowerShellDirect,omitempty"`
}
