/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

// Object describing a Container Credential Guard system request.
type ContainerCredentialGuardOperationRequest struct {
	Operation *ContainerCredentialGuardModifyOperation `json:"Operation,omitempty"`
	// Object describing the input properties used by the specified operation type.
	OperationDetails interface{} `json:"OperationDetails,omitempty"`
}
