/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

// Object describing a request to add a Container Credential Guard Instance.
type ContainerCredentialGuardAddInstanceRequest struct {
	// Globally unique identifier to use for the Container Credential Guard Instance.
	Id string `json:"Id,omitempty"`
	// JSON document as a string that describes the Container Credential Guard Instance's credential specification to use.
	CredentialSpec string `json:"CredentialSpec,omitempty"`
	Transport *ContainerCredentialGuardTransport `json:"Transport,omitempty"`
}
