/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

// Object listing the system's running Container Credential Guard Instances.
type ContainerCredentialGuardSystemInfo struct {
	// Array of running Container Credential Guard Instances.
	Instances []ContainerCredentialGuardInstance `json:"Instances,omitempty"`
}
