/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

// Create group operation settings
type CreateGroupOperation struct {
	GroupId string `json:"GroupId,omitempty"`
	LogicalProcessorCount int32 `json:"LogicalProcessorCount,omitempty"`
	LogicalProcessors []int32 `json:"LogicalProcessors,omitempty"`
}
