/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type DeviceType string

// List of DeviceType
const (
	DeviceTypeCLASS_GUID DeviceType = "ClassGuid"
	DeviceTypeDEVICE_INSTANCE DeviceType = "DeviceInstance"
	DeviceTypeGPU_MIRROR DeviceType = "GpuMirror"
)
