/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type Device struct {
	Type_ *DeviceType `json:"Type,omitempty"`
	// The interface class guid of the device interfaces to assign to the container. Only used when Type is ClassGuid.
	InterfaceClassGuid string `json:"InterfaceClassGuid,omitempty"`
	// The location path of the device to assign to the container. Only used when Type is DeviceInstance.
	LocationPath string `json:"LocationPath,omitempty"`
}
