/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type DeviceExtension struct {
	DeviceCategory *DeviceCategory `json:"device_category,omitempty"`
	Namespace *Namespace `json:"namespace,omitempty"`
}
