/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type Devices struct {
	// An optional object that maps COM Port objects for any ports configured on the virtual machine. The key in the map is the integer, starting from zero, that will identify the COM port into the guest.
	ComPorts map[string]ComPort `json:"ComPorts,omitempty"`
	VirtioSerial *VirtioSerial `json:"VirtioSerial,omitempty"`
	// An optional object that maps SCSI controllers, identified by friendly name. The provided name is hashed to create the controller's channel instance identifier. If the name is already a GUID, that GUID will be used as the channel instance identifier as-is.
	Scsi map[string]Scsi `json:"Scsi,omitempty"`
	VirtualPMem *VirtualPMemController `json:"VirtualPMem,omitempty"`
	// An optional object that maps network adapters, identified by friendly name. The provided name is hashed to create the adapter's instance identifier. If the name is already a GUID, that GUID will be used as the identifier as-is.
	NetworkAdapters map[string]NetworkAdapter `json:"NetworkAdapters,omitempty"`
	VideoMonitor *VideoMonitor `json:"VideoMonitor,omitempty"`
	Keyboard *Keyboard `json:"Keyboard,omitempty"`
	Mouse *Mouse `json:"Mouse,omitempty"`
	HvSocket *VirtualMachineHvSocket `json:"HvSocket,omitempty"`
	EnhancedModeVideo *EnhancedModeVideo `json:"EnhancedModeVideo,omitempty"`
	GuestCrashReporting *GuestCrashReporting `json:"GuestCrashReporting,omitempty"`
	VirtualSmb *VirtualSmb `json:"VirtualSmb,omitempty"`
	Plan9 *Plan9 `json:"Plan9,omitempty"`
	Battery *Battery `json:"Battery,omitempty"`
	// An optional object that maps flexible IoV devices, identified by friendly name. The provided name is hashed to create the device's instance identifier. If the name is already a GUID, that GUID will be used as the identifier as-is.
	FlexibleIov map[string]FlexibleIoDevice `json:"FlexibleIov,omitempty"`
	SharedMemory *SharedMemoryConfiguration `json:"SharedMemory,omitempty"`
	VirtualPci map[string]VirtualPciDevice `json:"VirtualPci,omitempty"`
}
