/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

// Error descriptor that provides the info of an error object
type ErrorEvent struct {
	// Fully formated error message
	Message string `json:"Message,omitempty"`
	// Stack trace in string form
	StackTrace string `json:"StackTrace,omitempty"`
	// Event definition
	Provider string `json:"Provider,omitempty"`
	// Event Id
	EventId int32 `json:"EventId,omitempty"`
	// Flags
	Flags int32 `json:"Flags,omitempty"`
	// Source
	Source string `json:"Source,omitempty"`
	// Event data
	Data []EventData `json:"Data,omitempty"`
}
