/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2
// EventDataType : Data types for event data elements, based on EVT_VARIANT_TYPE
type EventDataType string

// List of EventDataType
const (
	EventDataTypeEMPTY EventDataType = "Empty"
	EventDataTypeSTRING_ EventDataType = "String"
	EventDataTypeANSI_STRING EventDataType = "AnsiString"
	EventDataTypeS_BYTE EventDataType = "SByte"
	EventDataTypeBYTE_ EventDataType = "Byte"
	EventDataTypeINT16_ EventDataType = "Int16"
	EventDataTypeU_INT16 EventDataType = "UInt16"
	EventDataTypeINT32_ EventDataType = "Int32"
	EventDataTypeU_INT32 EventDataType = "UInt32"
	EventDataTypeINT64_ EventDataType = "Int64"
	EventDataTypeU_INT64 EventDataType = "UInt64"
	EventDataTypeSINGLE EventDataType = "Single"
	EventDataTypeDOUBLE EventDataType = "Double"
	EventDataTypeBOOLEAN EventDataType = "Boolean"
	EventDataTypeBINARY EventDataType = "Binary"
	EventDataTypeGUID EventDataType = "Guid"
)
