/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2
// ExitInitiator : Initiator of an exit (guest, management client, etc.)
type ExitInitiator string

// List of ExitInitiator
const (
	ExitInitiatorNONE ExitInitiator = "None"
	ExitInitiatorGUEST_OS ExitInitiator = "GuestOS"
	ExitInitiatorCLIENT ExitInitiator = "Client"
	ExitInitiatorINTERNAL ExitInitiator = "Internal"
	ExitInitiatorUNKNOWN ExitInitiator = "Unknown"
)
