/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type FilesystemNamespace struct {
	Path string `json:"path,omitempty"`
	Isolation *FilesystemIsolationMode `json:"isolation,omitempty"`
	Nesting *FilesystemNestingMode `json:"nesting,omitempty"`
	Layer []FilesystemLayer `json:"layer,omitempty"`
	Bindings []ContainersDefBatchedBinding `json:"bindings,omitempty"`
}
