/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2
// GetPropertyType : Service property type queried by HcsGetServiceProperties
type GetPropertyType string

// List of GetPropertyType
const (
	GetPropertyTypeBASIC GetPropertyType = "Basic"
	GetPropertyTypeCPU_GROUP GetPropertyType = "CpuGroup"
	GetPropertyTypePROCESSOR_TOPOLOGY GetPropertyType = "ProcessorTopology"
	GetPropertyTypeCONTAINER_CREDENTIAL_GUARD GetPropertyType = "ContainerCredentialGuard"
	GetPropertyTypeQO_S_CAPABILITIES GetPropertyType = "QoSCapabilities"
)
