/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type GpuAssignmentMode string

// List of GpuAssignmentMode
const (
	GpuAssignmentModeDISABLED GpuAssignmentMode = "Disabled"
	GpuAssignmentModeDEFAULT_ GpuAssignmentMode = "Default"
	GpuAssignmentModeLIST GpuAssignmentMode = "List"
	GpuAssignmentModeMIRROR GpuAssignmentMode = "Mirror"
)
