/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

// Properties of the guest operating system that boots on a Windows Server Container.
type GuestOs struct {
	// HostName assigned to a container guest operating system.
	HostName string `json:"HostName,omitempty"`
}
