/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type HostFiles struct {
	BaseImagePath string `json:"base_image_path,omitempty"`
	SandboxPath string `json:"sandbox_path,omitempty"`
	File []string `json:"file,omitempty"`
}
