/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

// Structure used to request a service processor modification
type HostProcessorModificationRequest struct {
	Operation *ModifyServiceOperation `json:"Operation,omitempty"`
	OperationDetails interface{} `json:"OperationDetails,omitempty"`
}
