/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2
// IntegrationComponentOperationalState : Operational status for integration component
type IntegrationComponentOperationalState string

// List of IntegrationComponentOperationalState
const (
	IntegrationComponentOperationalStateUNKNOWN IntegrationComponentOperationalState = "Unknown"
	IntegrationComponentOperationalStateDEGRADED IntegrationComponentOperationalState = "Degraded"
	IntegrationComponentOperationalStateDORMANT IntegrationComponentOperationalState = "Dormant"
	IntegrationComponentOperationalStateERROR_ IntegrationComponentOperationalState = "Error"
	IntegrationComponentOperationalStateLOST_COMMUNICATION IntegrationComponentOperationalState = "LostCommunication"
	IntegrationComponentOperationalStateNON_RECOVERABLE_ERROR IntegrationComponentOperationalState = "NonRecoverableError"
	IntegrationComponentOperationalStateNO_CONTACT IntegrationComponentOperationalState = "NoContact"
	IntegrationComponentOperationalStateOK IntegrationComponentOperationalState = "Ok"
)
