/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2
// InterfaceClassType : Enum used to specify how the interface class should be treated when applying a device extension/creating container symlinks. This enum is ordering-sensitive; if two interface classes with the same identifier are merged, the type of the resulting interface class is given by the larger enum value (e.g., DeviceInstance + ClassGuid = ClassGuid).
type InterfaceClassType string

// List of InterfaceClassType
const (
	InterfaceClassTypeINHERIT InterfaceClassType = "Inherit"
	InterfaceClassTypeDEVICE_INSTANCE InterfaceClassType = "DeviceInstance"
	InterfaceClassTypeCLASS_GUID InterfaceClassType = "ClassGuid"
)
