/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2
// InterruptModerationMode : The valid interrupt moderation modes for I/O virtualization (IOV) offloading.
type InterruptModerationMode string

// List of InterruptModerationMode
const (
	InterruptModerationModeDEFAULT_ InterruptModerationMode = "Default"
	InterruptModerationModeADAPTIVE InterruptModerationMode = "Adaptive"
	InterruptModerationModeOFF InterruptModerationMode = "Off"
	InterruptModerationModeLOW InterruptModerationMode = "Low"
	InterruptModerationModeMEDIUM InterruptModerationMode = "Medium"
	InterruptModerationModeHIGH InterruptModerationMode = "High"
)
