/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2
// IntegrationComponentOperatingStateReason : Possible reason for integration component's state
type IntegrationComponentOperatingStateReason string

// List of IntegrationComponentOperatingStateReason
const (
	IntegrationComponentOperatingStateReasonUNKNOWN IntegrationComponentOperatingStateReason = "Unknown"
	IntegrationComponentOperatingStateReasonAPPS_IN_CRITICAL_STATE IntegrationComponentOperatingStateReason = "AppsInCriticalState"
	IntegrationComponentOperatingStateReasonCOMMUNICATION_TIMED_OUT IntegrationComponentOperatingStateReason = "CommunicationTimedOut"
	IntegrationComponentOperatingStateReasonFAILED_COMMUNICATION IntegrationComponentOperatingStateReason = "FailedCommunication"
	IntegrationComponentOperatingStateReasonHEALTHY_APPS IntegrationComponentOperatingStateReason = "HealthyApps"
	IntegrationComponentOperatingStateReasonPROTOCOL_MISMATCH IntegrationComponentOperatingStateReason = "ProtocolMismatch"
)
