/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type IovSettings struct {
	// The weight assigned to this port for I/O virtualization (IOV) offloading. Setting this to 0 disables IOV offloading.
	OffloadWeight int32 `json:"OffloadWeight,omitempty"`
	// The number of queue pairs requested for this port for I/O virtualization (IOV) offloading.
	QueuePairsRequested int32 `json:"QueuePairsRequested,omitempty"`
	InterruptModeration *InterruptModerationMode `json:"InterruptModeration,omitempty"`
}
