/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type JobNamespace struct {
	Cpu *JobCpu `json:"cpu,omitempty"`
	Memory *JobMemory `json:"memory,omitempty"`
	Systemroot *JobSystemRoot `json:"systemroot,omitempty"`
	Terminationpolicy *JobTerminationPolicy `json:"terminationpolicy,omitempty"`
	Threadimpersonation bool `json:"threadimpersonation,omitempty"`
}
