/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type JobCpu struct {
	Rate int32 `json:"rate,omitempty"`
	Weight int32 `json:"weight,omitempty"`
}
