/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type KvpExchange struct {
	EnableHostOSInfoKvpItems *StateOverride `json:"EnableHostOSInfoKvpItems,omitempty"`
	EntriesToBeAdded map[string]string `json:"EntriesToBeAdded,omitempty"`
	EntriesToBeRemoved []string `json:"EntriesToBeRemoved,omitempty"`
}
