/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2
// KvpSource : The source sets the location of the key-value pairs stored depending on the type of the key-value pairs
type KvpSource string

// List of KvpSource
const (
	KvpSourceKVP_SET_BY_HOST KvpSource = "KvpSetByHost"
	KvpSourceKVP_SET_BY_GUEST KvpSource = "KvpSetByGuest"
	KvpSourceGUEST_OS_INFO KvpSource = "GuestOSInfo"
)
