/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type LogicalProcessor struct {
	LpIndex int32 `json:"LpIndex,omitempty"`
	NodeNumber int32 `json:"NodeNumber,omitempty"`
	PackageId int32 `json:"PackageId,omitempty"`
	CoreId int32 `json:"CoreId,omitempty"`
	RootVpIndex int32 `json:"RootVpIndex,omitempty"`
	Subnodes []Subnode `json:"Subnodes,omitempty"`
}
