/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

// The response of memory information for virtual machine when query memory propery of compute system
type MemoryInformationForVm struct {
	VirtualNodeCount int32 `json:"VirtualNodeCount,omitempty"`
	VirtualMachineMemory *VmMemory `json:"VirtualMachineMemory,omitempty"`
	VirtualNodes []VirtualNodeInfo `json:"VirtualNodes,omitempty"`
}
