/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2
// ModifyPropertyType : Service property type modified by HcsModifyServiceSettings
type ModifyPropertyType string

// List of ModifyPropertyType
const (
	ModifyPropertyTypeCPU_GROUP ModifyPropertyType = "CpuGroup"
	ModifyPropertyTypeCONTAINER_CREDENTIAL_GUARD ModifyPropertyType = "ContainerCredentialGuard"
)
