/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type ModifySettingRequest struct {
	ResourcePath string `json:"ResourcePath,omitempty"`
	RequestType *ModifyRequestType `json:"RequestType,omitempty"`
	Settings interface{} `json:"Settings,omitempty"`
	GuestRequest interface{} `json:"GuestRequest,omitempty"`
}
