/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2
// ModifyServiceOperation : Enumeration of different supported service processor modification requests
type ModifyServiceOperation string

// List of ModifyServiceOperation
const (
	ModifyServiceOperationCREATE_GROUP ModifyServiceOperation = "CreateGroup"
	ModifyServiceOperationDELETE_GROUP ModifyServiceOperation = "DeleteGroup"
	ModifyServiceOperationSET_PROPERTY ModifyServiceOperation = "SetProperty"
)
