/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type ModifyResourceType string

// List of ModifyResourceType
const (
	ModifyResourceTypeMEMORY ModifyResourceType = "Memory"
	ModifyResourceTypeMAPPED_DIRECTORY ModifyResourceType = "MappedDirectory"
	ModifyResourceTypeMAPPED_PIPE ModifyResourceType = "MappedPipe"
	ModifyResourceTypeMAPPED_VIRTUAL_DISK ModifyResourceType = "MappedVirtualDisk"
	ModifyResourceTypeCOMBINED_LAYERS ModifyResourceType = "CombinedLayers"
	ModifyResourceTypeNETWORK_NAMESPACE ModifyResourceType = "NetworkNamespace"
	ModifyResourceTypeCIM_MOUNT ModifyResourceType = "CimMount"
)
