/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type Namespace struct {
	Job *JobNamespace `json:"job,omitempty"`
	Filesystem *FilesystemNamespace `json:"filesystem,omitempty"`
	Mountmgr *MountManagerNamespace `json:"mountmgr,omitempty"`
	Namedpipe *NamedPipeNamespace `json:"namedpipe,omitempty"`
	Ob *ObjectNamespace `json:"ob,omitempty"`
	Registry *RegistryNamespace `json:"registry,omitempty"`
	Network *NetworkNamespace `json:"network,omitempty"`
	Device *DeviceNamespace `json:"device,omitempty"`
	Hostfiles *HostFiles `json:"hostfiles,omitempty"`
}
