/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type NetworkAdapter struct {
	EndpointId string `json:"EndpointId,omitempty"`
	MacAddress string `json:"MacAddress,omitempty"`
	InstanceId string `json:"InstanceId,omitempty"`
	// Disable interrupt batching (MNF) for network to decrease latency and increase throughput, at per-interrupt processing cost.
	DisableInterruptBatching bool `json:"DisableInterruptBatching,omitempty"`
	IovSettings *IovSettings `json:"IovSettings,omitempty"`
	ConnectionState *StateOverride `json:"ConnectionState,omitempty"`
}
