/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2
// NotificationType : Exit type of a compute system.
type NotificationType string

// List of NotificationType
const (
	NotificationTypeNONE NotificationType = "None"
	NotificationTypeGRACEFUL_EXIT NotificationType = "GracefulExit"
	NotificationTypeFORCED_EXIT NotificationType = "ForcedExit"
	NotificationTypeUNEXPECTED_EXIT NotificationType = "UnexpectedExit"
	NotificationTypeUNKNOWN NotificationType = "Unknown"
)
