/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type OperationType string

// List of OperationType
const (
	OperationTypeNONE OperationType = "None"
	OperationTypeCONSTRUCT OperationType = "Construct"
	OperationTypeSTART OperationType = "Start"
	OperationTypePAUSE OperationType = "Pause"
	OperationTypeRESUME OperationType = "Resume"
	OperationTypeSHUTDOWN OperationType = "Shutdown"
	OperationTypeTERMINATE OperationType = "Terminate"
	OperationTypeSAVE OperationType = "Save"
	OperationTypeGET_PROPERTIES OperationType = "GetProperties"
	OperationTypeMODIFY OperationType = "Modify"
	OperationTypeCRASH OperationType = "Crash"
	OperationTypeEXECUTE_PROCESS OperationType = "ExecuteProcess"
	OperationTypeGET_PROCESS_INFO OperationType = "GetProcessInfo"
	OperationTypeSIGNAL_PROCESS OperationType = "SignalProcess"
	OperationTypeMODIFY_PROCESS OperationType = "ModifyProcess"
	OperationTypeCANCEL_OPERATION OperationType = "CancelOperation"
)
