/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type OperationFailureDetail string

// List of OperationFailureDetail
const (
	OperationFailureDetailINVALID OperationFailureDetail = "Invalid"
	OperationFailureDetailCREATE_INTERNAL_ERROR OperationFailureDetail = "CreateInternalError"
	OperationFailureDetailCONSTRUCT_STATE_ERROR OperationFailureDetail = "ConstructStateError"
	OperationFailureDetailRUNTIME_OS_TYPE_MISMATCH OperationFailureDetail = "RuntimeOsTypeMismatch"
	OperationFailureDetailCONSTRUCT OperationFailureDetail = "Construct"
	OperationFailureDetailSTART OperationFailureDetail = "Start"
	OperationFailureDetailPAUSE OperationFailureDetail = "Pause"
	OperationFailureDetailRESUME OperationFailureDetail = "Resume"
	OperationFailureDetailSHUTDOWN OperationFailureDetail = "Shutdown"
	OperationFailureDetailTERMINATE OperationFailureDetail = "Terminate"
	OperationFailureDetailSAVE OperationFailureDetail = "Save"
	OperationFailureDetailGET_PROPERTIES OperationFailureDetail = "GetProperties"
	OperationFailureDetailMODIFY OperationFailureDetail = "Modify"
	OperationFailureDetailCRASH OperationFailureDetail = "Crash"
	OperationFailureDetailGUEST_CRASH OperationFailureDetail = "GuestCrash"
	OperationFailureDetailLIFECYCLE_NOTIFY OperationFailureDetail = "LifecycleNotify"
	OperationFailureDetailEXECUTE_PROCESS OperationFailureDetail = "ExecuteProcess"
	OperationFailureDetailGET_PROCESS_INFO OperationFailureDetail = "GetProcessInfo"
	OperationFailureDetailWAIT_FOR_PROCESS OperationFailureDetail = "WaitForProcess"
	OperationFailureDetailSIGNAL_PROCESS OperationFailureDetail = "SignalProcess"
	OperationFailureDetailMODIFY_PROCESS OperationFailureDetail = "ModifyProcess"
	OperationFailureDetailPREPARE_FOR_HOSTING OperationFailureDetail = "PrepareForHosting"
	OperationFailureDetailREGISTER_HOSTED_SYSTEM OperationFailureDetail = "RegisterHostedSystem"
	OperationFailureDetailUNREGISTER_HOSTED_SYSTEM OperationFailureDetail = "UnregisterHostedSystem"
	OperationFailureDetailPREPARE_FOR_CLONE OperationFailureDetail = "PrepareForClone"
	OperationFailureDetailGET_CLONE_TEMPLATE OperationFailureDetail = "GetCloneTemplate"
)
