/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

import (
	"time"
)

// / Information about an operation on a compute system. / An operation is typically an HCS API call but can also be something like / a compute system exit or crash.
type OperationInfo struct {
	Operation *OperationType `json:"Operation,omitempty"`
	// / Start time of the opertation
	StartTimestamp time.Time `json:"StartTimestamp,omitempty"`
	// / End time of the opertation
	EndTimestamp time.Time `json:"EndTimestamp,omitempty"`
	FailureInfo *OperationFailureInfo `json:"FailureInfo,omitempty"`
}
