/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type OsType string

// List of OsType
const (
	OsTypeEMPTY OsType = ""
	OsTypeWINDOWS OsType = "Windows"
	OsTypeLINUX OsType = "Linux"
)
