/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2
// PauseReason : Pause reason that is indicated to components running in the Virtual Machine.
type PauseReason string

// List of PauseReason
const (
	PauseReasonNONE PauseReason = "None"
	PauseReasonSAVE PauseReason = "Save"
	PauseReasonTEMPLATE PauseReason = "Template"
)
