/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type PauseSuspensionLevel string

// List of PauseSuspensionLevel
const (
	PauseSuspensionLevelSUSPEND PauseSuspensionLevel = "Suspend"
	PauseSuspensionLevelMEMORY_LOW PauseSuspensionLevel = "MemoryLow"
	PauseSuspensionLevelMEMORY_MEDIUM PauseSuspensionLevel = "MemoryMedium"
	PauseSuspensionLevelMEMORY_HIGH PauseSuspensionLevel = "MemoryHigh"
)
