/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type Plan9Share struct {
	Name string `json:"Name,omitempty"`
	// The name by which the guest operation system can access this share, via the aname parameter in the Plan9 protocol.
	AccessName string `json:"AccessName,omitempty"`
	Path string `json:"Path,omitempty"`
	Port int32 `json:"Port,omitempty"`
	AllowedFiles []string `json:"AllowedFiles,omitempty"`
}
