/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

// Used when modifying processor scheduling limits of a virtual machine.
type ProcessorLimits struct {
	// Maximum amount of host CPU resources that the virtual machine can use.
	Limit int32 `json:"Limit,omitempty"`
	// Value describing the relative priority of this virtual machine compared to other virtual machines.
	Weight int32 `json:"Weight,omitempty"`
	// Minimum amount of host CPU resources that the virtual machine is guaranteed.
	Reservation int32 `json:"Reservation,omitempty"`
	// Provides the target maximum CPU frequency, in MHz, for a virtual machine.
	MaximumFrequencyMHz int32 `json:"MaximumFrequencyMHz,omitempty"`
}
