/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

// Provided in the EventData parameter of an HcsEventProcessExited HCS_EVENT.
type ProcessStatus struct {
	// The process id (PID) of the process.
	ProcessId int32 `json:"ProcessId,omitempty"`
	// True if the process has exited, false if it has not exited yet.
	Exited bool `json:"Exited,omitempty"`
	// Exit code of the process. The ExitCode is valid only if LastWaitResult is S_OK and Exited is true.
	ExitCode int32 `json:"ExitCode,omitempty"`
	// Status of waiting for process exit. S_OK indicates success. Other HRESULT values on error.
	LastWaitResult int32 `json:"LastWaitResult,omitempty"`
}
