/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

// Structure used to return processor topology for a Service property query
type ProcessorTopology struct {
	LogicalProcessorCount int32 `json:"LogicalProcessorCount,omitempty"`
	LogicalProcessors []LogicalProcessor `json:"LogicalProcessors,omitempty"`
}
