/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type ProcessSignal string

// List of ProcessSignal
const (
	ProcessSignalCTRL_C ProcessSignal = "CtrlC"
	ProcessSignalCTRL_BREAK ProcessSignal = "CtrlBreak"
	ProcessSignalCTRL_CLOSE ProcessSignal = "CtrlClose"
	ProcessSignalCTRL_LOG_OFF ProcessSignal = "CtrlLogOff"
	ProcessSignalCTRL_SHUTDOWN ProcessSignal = "CtrlShutdown"
)
