/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type Properties struct {
	Id string `json:"Id,omitempty"`
	SystemType *SystemType `json:"SystemType,omitempty"`
	RuntimeOsType *OsType `json:"RuntimeOsType,omitempty"`
	Name string `json:"Name,omitempty"`
	Owner string `json:"Owner,omitempty"`
	RuntimeId string `json:"RuntimeId,omitempty"`
	RuntimeTemplateId string `json:"RuntimeTemplateId,omitempty"`
	State *State `json:"State,omitempty"`
	Stopped bool `json:"Stopped,omitempty"`
	ExitType *NotificationType `json:"ExitType,omitempty"`
	Memory *MemoryInformationForVm `json:"Memory,omitempty"`
	Statistics *Statistics `json:"Statistics,omitempty"`
	ProcessList []ProcessDetails `json:"ProcessList,omitempty"`
	TerminateOnLastHandleClosed bool `json:"TerminateOnLastHandleClosed,omitempty"`
	HostingSystemId string `json:"HostingSystemId,omitempty"`
	SharedMemoryRegionInfo []SharedMemoryRegionInfo `json:"SharedMemoryRegionInfo,omitempty"`
	GuestConnectionInfo *GuestConnectionInfo `json:"GuestConnectionInfo,omitempty"`
	// This is a new response object, introduced in version 2.5, which maps the requested property names to their associated response objects.
	PropertyResponses map[string]PropertyResponse `json:"PropertyResponses,omitempty"`
}
