/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type RegistryValueType string

// List of RegistryValueType
const (
	RegistryValueTypeNONE RegistryValueType = "None"
	RegistryValueTypeSTRING_ RegistryValueType = "String"
	RegistryValueTypeEXPANDED_STRING RegistryValueType = "ExpandedString"
	RegistryValueTypeMULTI_STRING RegistryValueType = "MultiString"
	RegistryValueTypeBINARY RegistryValueType = "Binary"
	RegistryValueTypeD_WORD RegistryValueType = "DWord"
	RegistryValueTypeQ_WORD RegistryValueType = "QWord"
	RegistryValueTypeCUSTOM_TYPE RegistryValueType = "CustomType"
)
