/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type RegistryLayer struct {
	Hosthive string `json:"hosthive,omitempty"`
	Filepath string `json:"filepath,omitempty"`
	Identifier string `json:"identifier,omitempty"`
	Readonly bool `json:"readonly,omitempty"`
	Immutable bool `json:"immutable,omitempty"`
	Inherittrustclass bool `json:"inherittrustclass,omitempty"`
	Trustedhive bool `json:"trustedhive,omitempty"`
	Writethrough bool `json:"writethrough,omitempty"`
	// The FileAccessToken field should only be used in-memory and not serialized/deserialized, since it refers to a token handle.
	Fileaccesstoken int32 `json:"fileaccesstoken,omitempty"`
}
