/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type RegistryMakeValue struct {
	Name string `json:"name,omitempty"`
	DataMultistring string `json:"data_multistring,omitempty"`
	DataDword int32 `json:"data_dword,omitempty"`
	DataString string `json:"data_string,omitempty"`
	DataBinary string `json:"data_binary,omitempty"`
}
