/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type RegistryMakeKey struct {
	Name string `json:"name,omitempty"`
	Clonesd string `json:"clonesd,omitempty"`
	Mkkey []RegistryMakeKey `json:"mkkey,omitempty"`
	Mkvalue []RegistryMakeValue `json:"mkvalue,omitempty"`
	Volatile bool `json:"volatile,omitempty"`
}
