/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type SaveOptions struct {
	SaveType *SaveType `json:"SaveType,omitempty"`
	// The path to the file that will container the saved state.
	SaveStateFilePath string `json:"SaveStateFilePath,omitempty"`
}
