/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

// Object describing a SCSI controller.
type Scsi struct {
	// Map of attachments, where the key is the integer LUN number on the controller.
	Attachments map[string]Attachment `json:"Attachments,omitempty"`
	// Disable interrupt batching (MNF) for storage to decrease latency and increase throughput, at per-interrupt processing cost.
	DisableInterruptBatching bool `json:"DisableInterruptBatching,omitempty"`
}
