/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type SerialConsole string

// List of SerialConsole
const (
	SerialConsoleDEFAULT_ SerialConsole = "Default"
	SerialConsoleDISABLED SerialConsole = "Disabled"
	SerialConsoleCOM_PORT1 SerialConsole = "ComPort1"
	SerialConsoleCOM_PORT2 SerialConsole = "ComPort2"
)
