/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type Services struct {
	Heartbeat *Heartbeat `json:"Heartbeat,omitempty"`
	Shutdown *Shutdown `json:"Shutdown,omitempty"`
	Timesync *Timesync `json:"Timesync,omitempty"`
	KvpExchange *KvpExchange `json:"KvpExchange,omitempty"`
}
