/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

// Properties of the host
type ServiceProperties struct {
	// The service properties will be returned as an array corresponding to the requested property types.
	Properties []interface{} `json:"Properties,omitempty"`
	// This is a response object, introduced in version 2.5, which takes the name of the property and its associated query object if needed
	PropertyResponses map[string]PropertyResponse `json:"PropertyResponses,omitempty"`
}
