/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

// Structure used to perform property query
type ServicePropertyQuery struct {
	// Specifies the property array to query
	PropertyTypes []GetPropertyType `json:"PropertyTypes,omitempty"`
	PropertyQueries map[string]interface{} `json:"PropertyQueries,omitempty"`
}
