/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2
// ShutdownMechanism : Different mechanisms to perform a shutdown operation
type ShutdownMechanism string

// List of ShutdownMechanism
const (
	ShutdownMechanismGUEST_CONNECTION ShutdownMechanism = "GuestConnection"
	ShutdownMechanismINTEGRATION_SERVICE ShutdownMechanism = "IntegrationService"
)
