/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2
// ShutdownType : Different operations that are related or classified as a type of shutdown
type ShutdownType string

// List of ShutdownType
const (
	ShutdownTypeSHUTDOWN ShutdownType = "Shutdown"
	ShutdownTypeHIBERNATE ShutdownType = "Hibernate"
	ShutdownTypeREBOOT ShutdownType = "Reboot"
)
