/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

// Options for HcsShutdownComputeSystem
type ShutdownOptions struct {
	Mechanism *ShutdownMechanism `json:"Mechanism,omitempty"`
	Type_ *ShutdownType `json:"Type,omitempty"`
	// If this shutdown is forceful or not
	Force bool `json:"Force,omitempty"`
	// Reason for the shutdown
	Reason string `json:"Reason,omitempty"`
}
