/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2
// State : Compute system state which is exposed to external clients
type State string

// List of State
const (
	StateCREATED State = "Created"
	StateRUNNING State = "Running"
	StatePAUSED State = "Paused"
	StateSTOPPED State = "Stopped"
	StateSAVED_AS_TEMPLATE State = "SavedAsTemplate"
	StateUNKNOWN State = "Unknown"
)
