/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type StateOverride string

// List of StateOverride
const (
	StateOverrideDEFAULT_ StateOverride = "Default"
	StateOverrideDISABLED StateOverride = "Disabled"
	StateOverrideENABLED StateOverride = "Enabled"
)
