/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type SubnodeType string

// List of SubnodeType
const (
	SubnodeTypeANY SubnodeType = "Any"
	SubnodeTypeSOCKET SubnodeType = "Socket"
	SubnodeTypeCLUSTER SubnodeType = "Cluster"
	SubnodeTypeL3 SubnodeType = "L3"
)
