/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type SystemExitDetail string

// List of SystemExitDetail
const (
	SystemExitDetailINVALID SystemExitDetail = "Invalid"
	SystemExitDetailHCS_API_FATAL_ERROR SystemExitDetail = "HcsApiFatalError"
	SystemExitDetailSERVICE_STOP SystemExitDetail = "ServiceStop"
	SystemExitDetailSHUTDOWN SystemExitDetail = "Shutdown"
	SystemExitDetailTERMINATE SystemExitDetail = "Terminate"
	SystemExitDetailUNEXPECTED_EXIT SystemExitDetail = "UnexpectedExit"
)
