/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

// By default the basic properties will be returned. This query provides a way to request specific properties.
type SystemPropertyQuery struct {
	PropertyTypes []SystemPropertyType `json:"PropertyTypes,omitempty"`
	// This is a new property request object, introduced in version 2.5, which takes the names of the properties and their associated query objects if needed.
	Queries map[string]interface{} `json:"Queries,omitempty"`
}
