/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type SystemType string

// List of SystemType
const (
	SystemTypeCONTAINER SystemType = "Container"
	SystemTypeVIRTUAL_MACHINE SystemType = "VirtualMachine"
)
