/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2
// SystemPropertyType : Compute system property types. The properties will be returned as a Schema.Responses.System.Properties instance.
type SystemPropertyType string

// List of System_PropertyType
const (
	SystemPropertyTypeMEMORY SystemPropertyType = "Memory"
	SystemPropertyTypeSTATISTICS SystemPropertyType = "Statistics"
	SystemPropertyTypePROCESS_LIST SystemPropertyType = "ProcessList"
	SystemPropertyTypeTERMINATE_ON_LAST_HANDLE_CLOSED SystemPropertyType = "TerminateOnLastHandleClosed"
	SystemPropertyTypeSHARED_MEMORY_REGION SystemPropertyType = "SharedMemoryRegion"
	SystemPropertyTypeGUEST_CONNECTION SystemPropertyType = "GuestConnection"
)
