/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type Uefi struct {
	EnableDebugger bool `json:"EnableDebugger,omitempty"`
	SecureBootTemplateId string `json:"SecureBootTemplateId,omitempty"`
	ApplySecureBootTemplate *ApplySecureBootTemplateType `json:"ApplySecureBootTemplate,omitempty"`
	BootThis *UefiBootEntry `json:"BootThis,omitempty"`
	Console *SerialConsole `json:"Console,omitempty"`
	StopOnBootFailure bool `json:"StopOnBootFailure,omitempty"`
}
