/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type UefiBootDevice string

// List of UefiBootDevice
const (
	UefiBootDeviceSCSI_DRIVE UefiBootDevice = "ScsiDrive"
	UefiBootDeviceVMB_FS UefiBootDevice = "VmbFs"
	UefiBootDeviceNETWORK UefiBootDevice = "Network"
	UefiBootDeviceFILE UefiBootDevice = "File"
)
