/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

// Object that describes a version with a Major.Minor format.
type Version struct {
	// The major version value. Individual major versions are not compatible with one another.
	Major int32 `json:"Major,omitempty"`
	// The minor version value. A lower minor version is considered a compatible subset of a higher minor version.
	Minor int32 `json:"Minor,omitempty"`
}
