/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type VirtualPciFunction struct {
	DeviceInstancePath string `json:"DeviceInstancePath,omitempty"`
	VirtualFunction int32 `json:"VirtualFunction,omitempty"`
	AllowDirectTranslatedP2P bool `json:"AllowDirectTranslatedP2P,omitempty"`
}
