/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type VirtualPMemDevice struct {
	HostPath string `json:"HostPath,omitempty"`
	ReadOnly bool `json:"ReadOnly,omitempty"`
	ImageFormat *VirtualPMemImageFormat `json:"ImageFormat,omitempty"`
	SizeBytes int32 `json:"SizeBytes,omitempty"`
	Mappings map[string]VirtualPMemMapping `json:"Mappings,omitempty"`
}
