/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type VirtualMachineProcessor struct {
	Count int32 `json:"Count,omitempty"`
	Limit int32 `json:"Limit,omitempty"`
	Weight int32 `json:"Weight,omitempty"`
	Reservation int32 `json:"Reservation,omitempty"`
	// Provides the target maximum CPU frequency, in MHz, for a virtual machine.
	MaximumFrequencyMHz int32 `json:"MaximumFrequencyMHz,omitempty"`
	ExposeVirtualizationExtensions bool `json:"ExposeVirtualizationExtensions,omitempty"`
	EnablePerfmonPmu bool `json:"EnablePerfmonPmu,omitempty"`
	EnablePerfmonPebs bool `json:"EnablePerfmonPebs,omitempty"`
	EnablePerfmonLbr bool `json:"EnablePerfmonLbr,omitempty"`
	EnablePerfmonIpt bool `json:"EnablePerfmonIpt,omitempty"`
	CpuGroup *CpuGroup `json:"CpuGroup,omitempty"`
}
