/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type VirtioSerialPort struct {
	// Pipe name to connect to this port from the host.
	NamedPipe string `json:"NamedPipe,omitempty"`
	// Friendly name provided to the guest.
	Name string `json:"Name,omitempty"`
	// Indicates to the guest that this port can be used as a console.
	ConsoleSupport bool `json:"ConsoleSupport,omitempty"`
}
