/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

// Provides information on failures originated by a virtual device.
type VirtualDeviceFailure struct {
	Detail *VirtualDeviceFailureDetail `json:"Detail,omitempty"`
	// Friendly name of the virtual device.
	Name string `json:"Name,omitempty"`
	// Id of the virtual device.
	DeviceId string `json:"DeviceId,omitempty"`
	// Instance Id of the virtual device.
	InstanceId string `json:"InstanceId,omitempty"`
}
