/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2
// VirtualDeviceFailureDetail : Provides detail on the context in which a virtual device failed.
type VirtualDeviceFailureDetail string

// List of VirtualDeviceFailureDetail
const (
	VirtualDeviceFailureDetailNONE VirtualDeviceFailureDetail = "None"
	VirtualDeviceFailureDetailCREATE VirtualDeviceFailureDetail = "Create"
	VirtualDeviceFailureDetailINITIALIZE VirtualDeviceFailureDetail = "Initialize"
	VirtualDeviceFailureDetailSTART_RESERVING_RESOURCES VirtualDeviceFailureDetail = "StartReservingResources"
	VirtualDeviceFailureDetailFINISH_RESERVING_RESOURCES VirtualDeviceFailureDetail = "FinishReservingResources"
	VirtualDeviceFailureDetailFREE_RESERVED_RESOURCES VirtualDeviceFailureDetail = "FreeReservedResources"
	VirtualDeviceFailureDetailSAVE_RESERVED_RESOURCES VirtualDeviceFailureDetail = "SaveReservedResources"
	VirtualDeviceFailureDetailPOWER_ON_COLD VirtualDeviceFailureDetail = "PowerOnCold"
	VirtualDeviceFailureDetailPOWER_ON_RESTORE VirtualDeviceFailureDetail = "PowerOnRestore"
	VirtualDeviceFailureDetailPOWER_OFF VirtualDeviceFailureDetail = "PowerOff"
	VirtualDeviceFailureDetailSAVE VirtualDeviceFailureDetail = "Save"
	VirtualDeviceFailureDetailRESUME VirtualDeviceFailureDetail = "Resume"
	VirtualDeviceFailureDetailPAUSE VirtualDeviceFailureDetail = "Pause"
	VirtualDeviceFailureDetailENABLE_OPTIMIZATIONS VirtualDeviceFailureDetail = "EnableOptimizations"
	VirtualDeviceFailureDetailSTART_DISABLE_OPTIMIZATIONS VirtualDeviceFailureDetail = "StartDisableOptimizations"
	VirtualDeviceFailureDetailFINISH_DISABLE_OPTIMIZATIONS VirtualDeviceFailureDetail = "FinishDisableOptimizations"
	VirtualDeviceFailureDetailRESET VirtualDeviceFailureDetail = "Reset"
	VirtualDeviceFailureDetailPOST_RESET VirtualDeviceFailureDetail = "PostReset"
	VirtualDeviceFailureDetailTEARDOWN VirtualDeviceFailureDetail = "Teardown"
	VirtualDeviceFailureDetailSAVE_COMPATIBILITY_INFO VirtualDeviceFailureDetail = "SaveCompatibilityInfo"
	VirtualDeviceFailureDetailMETRIC_RESTORE VirtualDeviceFailureDetail = "MetricRestore"
	VirtualDeviceFailureDetailMETRIC_ENUMERATE VirtualDeviceFailureDetail = "MetricEnumerate"
	VirtualDeviceFailureDetailMETRIC_ENUMERATE_FOR_SAVE VirtualDeviceFailureDetail = "MetricEnumerateForSave"
	VirtualDeviceFailureDetailMETRIC_RESET VirtualDeviceFailureDetail = "MetricReset"
	VirtualDeviceFailureDetailMETRIC_ENABLE VirtualDeviceFailureDetail = "MetricEnable"
	VirtualDeviceFailureDetailMETRIC_DISABLE VirtualDeviceFailureDetail = "MetricDisable"
)
