/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2
// WindowsCrashPhase : Indicated the progress of a Windows memory dump in a WindowsCrashReport.
type WindowsCrashPhase string

// List of WindowsCrashPhase
const (
	WindowsCrashPhaseINACTIVE WindowsCrashPhase = "Inactive"
	WindowsCrashPhaseCRASH_VALUES WindowsCrashPhase = "CrashValues"
	WindowsCrashPhaseSTARTING WindowsCrashPhase = "Starting"
	WindowsCrashPhaseSTARTED WindowsCrashPhase = "Started"
	WindowsCrashPhaseWRITING WindowsCrashPhase = "Writing"
	WindowsCrashPhaseCOMPLETE WindowsCrashPhase = "Complete"
)
