/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2
// WorkerExitDetail : Detailed reasons for a VM stop
type WorkerExitDetail string

// List of WorkerExitDetail
const (
	WorkerExitDetailINVALID WorkerExitDetail = "Invalid"
	WorkerExitDetailPOWER_OFF WorkerExitDetail = "PowerOff"
	WorkerExitDetailPOWER_OFF_CRITICAL WorkerExitDetail = "PowerOffCritical"
	WorkerExitDetailRESET WorkerExitDetail = "Reset"
	WorkerExitDetailGUEST_CRASH WorkerExitDetail = "GuestCrash"
	WorkerExitDetailGUEST_FIRMWARE_CRASH WorkerExitDetail = "GuestFirmwareCrash"
	WorkerExitDetailTRIPLE_FAULT WorkerExitDetail = "TripleFault"
	WorkerExitDetailDEVICE_FATAL_APIC_REQUEST WorkerExitDetail = "DeviceFatalApicRequest"
	WorkerExitDetailDEVICE_FATAL_MSR_REQUEST WorkerExitDetail = "DeviceFatalMsrRequest"
	WorkerExitDetailDEVICE_FATAL_EXCEPTION WorkerExitDetail = "DeviceFatalException"
	WorkerExitDetailDEVICE_FATAL_ERROR WorkerExitDetail = "DeviceFatalError"
	WorkerExitDetailDEVICE_MACHINE_CHECK WorkerExitDetail = "DeviceMachineCheck"
	WorkerExitDetailEMULATOR_ERROR WorkerExitDetail = "EmulatorError"
	WorkerExitDetailVID_TERMINATE WorkerExitDetail = "VidTerminate"
	WorkerExitDetailPROCESS_UNEXPECTED_EXIT WorkerExitDetail = "ProcessUnexpectedExit"
	WorkerExitDetailINITIALIZATION_FAILURE WorkerExitDetail = "InitializationFailure"
	WorkerExitDetailINITIALIZATION_START_TIMEOUT WorkerExitDetail = "InitializationStartTimeout"
	WorkerExitDetailCOLD_START_FAILURE WorkerExitDetail = "ColdStartFailure"
	WorkerExitDetailRESET_START_FAILURE WorkerExitDetail = "ResetStartFailure"
	WorkerExitDetailFAST_RESTORE_START_FAILURE WorkerExitDetail = "FastRestoreStartFailure"
	WorkerExitDetailRESTORE_START_FAILURE WorkerExitDetail = "RestoreStartFailure"
	WorkerExitDetailFAST_SAVE_PRESERVE_PARTITION WorkerExitDetail = "FastSavePreservePartition"
	WorkerExitDetailFAST_SAVE_PRESERVE_PARTITION_HANDLE_TRANSFER WorkerExitDetail = "FastSavePreservePartitionHandleTransfer"
	WorkerExitDetailFAST_SAVE WorkerExitDetail = "FastSave"
	WorkerExitDetailCLONE_TEMPLATE WorkerExitDetail = "CloneTemplate"
	WorkerExitDetailSAVE WorkerExitDetail = "Save"
	WorkerExitDetailMIGRATE WorkerExitDetail = "Migrate"
	WorkerExitDetailMIGRATE_FAILURE WorkerExitDetail = "MigrateFailure"
	WorkerExitDetailCANNOT_REFERENCE_VM WorkerExitDetail = "CannotReferenceVm"
	WorkerExitDetailMGOT_UNREGISTER WorkerExitDetail = "MgotUnregister"
	WorkerExitDetailFAST_SAVE_PRESERVE_PARTITION_HANDLE_TRANSFER_STORAGE WorkerExitDetail = "FastSavePreservePartitionHandleTransferStorage"
	WorkerExitDetailFAST_SAVE_PRESERVE_PARTITION_HANDLE_TRANSFER_NETWORKING WorkerExitDetail = "FastSavePreservePartitionHandleTransferNetworking"
	WorkerExitDetailFAST_SAVE_PRESERVE_PARTITION_HANDLE_TRANSFER_STORAGE_AND_NETWORKING WorkerExitDetail = "FastSavePreservePartitionHandleTransferStorageAndNetworking"
	WorkerExitDetailFAST_SAVE_PRESERVE_PARTITION_HSR WorkerExitDetail = "FastSavePreservePartitionHsr"
)
