/*
 * Schema Open API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.4
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hcsschema2

type WorkerExitType string

// List of WorkerExitType
const (
	WorkerExitTypeNONE WorkerExitType = "None"
	WorkerExitTypeINITIALIZATION_FAILED WorkerExitType = "InitializationFailed"
	WorkerExitTypeSTOPPED WorkerExitType = "Stopped"
	WorkerExitTypeSAVED WorkerExitType = "Saved"
	WorkerExitTypeSTOPPED_ON_RESET WorkerExitType = "StoppedOnReset"
	WorkerExitTypeUNEXPECTED_STOP WorkerExitType = "UnexpectedStop"
	WorkerExitTypeRESET_FAILED WorkerExitType = "ResetFailed"
	WorkerExitTypeUNRECOVERABLE_ERROR WorkerExitType = "UnrecoverableError"
)
