// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: dev.azure.com/msazure/ContainerPlatform/_git/azcri.git/api/save/save.proto

package save

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartSaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PodId string `protobuf:"bytes,1,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	Path  string `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *StartSaveRequest) Reset() {
	*x = StartSaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSaveRequest) ProtoMessage() {}

func (x *StartSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSaveRequest.ProtoReflect.Descriptor instead.
func (*StartSaveRequest) Descriptor() ([]byte, []int) {
	return file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_rawDescGZIP(), []int{0}
}

func (x *StartSaveRequest) GetPodId() string {
	if x != nil {
		return x.PodId
	}
	return ""
}

func (x *StartSaveRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StartSaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartSaveResponse) Reset() {
	*x = StartSaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartSaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSaveResponse) ProtoMessage() {}

func (x *StartSaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSaveResponse.ProtoReflect.Descriptor instead.
func (*StartSaveResponse) Descriptor() ([]byte, []int) {
	return file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_rawDescGZIP(), []int{1}
}

type CompleteSaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PodId string `protobuf:"bytes,1,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
}

func (x *CompleteSaveRequest) Reset() {
	*x = CompleteSaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteSaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteSaveRequest) ProtoMessage() {}

func (x *CompleteSaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteSaveRequest.ProtoReflect.Descriptor instead.
func (*CompleteSaveRequest) Descriptor() ([]byte, []int) {
	return file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteSaveRequest) GetPodId() string {
	if x != nil {
		return x.PodId
	}
	return ""
}

type CompleteSaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CompleteSaveResponse) Reset() {
	*x = CompleteSaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompleteSaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteSaveResponse) ProtoMessage() {}

func (x *CompleteSaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteSaveResponse.ProtoReflect.Descriptor instead.
func (*CompleteSaveResponse) Descriptor() ([]byte, []int) {
	return file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_rawDescGZIP(), []int{3}
}

var File_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto protoreflect.FileDescriptor

var file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_rawDesc = []byte{
	0x0a, 0x4a, 0x64, 0x65, 0x76, 0x2e, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6d, 0x73, 0x61, 0x7a, 0x75, 0x72, 0x65, 0x2f, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65,
	0x72, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x2f, 0x5f, 0x67, 0x69, 0x74, 0x2f, 0x61,
	0x7a, 0x63, 0x72, 0x69, 0x2e, 0x67, 0x69, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x61, 0x76,
	0x65, 0x2f, 0x73, 0x61, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x64, 0x69, 0x61, 0x67, 0x22, 0x3d, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x70,
	0x6f, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6f, 0x64,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53,
	0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x2c, 0x0a, 0x13, 0x43,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x15, 0x0a, 0x06, 0x70, 0x6f, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x70, 0x6f, 0x64, 0x49, 0x64, 0x22, 0x16, 0x0a, 0x14, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x32, 0xdf, 0x01, 0x0a, 0x04, 0x53, 0x61, 0x76, 0x65, 0x12, 0x66, 0x0a, 0x09, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x53, 0x61, 0x76, 0x65, 0x12, 0x2b, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x64, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x64,
	0x69, 0x61, 0x67, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x64, 0x2e, 0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x64, 0x69, 0x61, 0x67,
	0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x6f, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x61,
	0x76, 0x65, 0x12, 0x2e, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e,
	0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x64, 0x69, 0x61, 0x67, 0x2e, 0x43,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x64, 0x2e,
	0x72, 0x75, 0x6e, 0x68, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x64, 0x69, 0x61, 0x67, 0x2e, 0x43,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x31, 0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x4d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x6f, 0x66, 0x74, 0x2f, 0x68, 0x63, 0x73, 0x73,
	0x68, 0x69, 0x6d, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x61, 0x76,
	0x65, 0x3b, 0x73, 0x61, 0x76, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_rawDescOnce sync.Once
	file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_rawDescData = file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_rawDesc
)

func file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_rawDescGZIP() []byte {
	file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_rawDescOnce.Do(func() {
		file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_rawDescData = protoimpl.X.CompressGZIP(file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_rawDescData)
	})
	return file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_rawDescData
}

var file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_goTypes = []interface{}{
	(*StartSaveRequest)(nil),     // 0: containerd.runhcs.v1.diag.StartSaveRequest
	(*StartSaveResponse)(nil),    // 1: containerd.runhcs.v1.diag.StartSaveResponse
	(*CompleteSaveRequest)(nil),  // 2: containerd.runhcs.v1.diag.CompleteSaveRequest
	(*CompleteSaveResponse)(nil), // 3: containerd.runhcs.v1.diag.CompleteSaveResponse
}
var file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_depIdxs = []int32{
	0, // 0: containerd.runhcs.v1.diag.Save.StartSave:input_type -> containerd.runhcs.v1.diag.StartSaveRequest
	2, // 1: containerd.runhcs.v1.diag.Save.CompleteSave:input_type -> containerd.runhcs.v1.diag.CompleteSaveRequest
	1, // 2: containerd.runhcs.v1.diag.Save.StartSave:output_type -> containerd.runhcs.v1.diag.StartSaveResponse
	3, // 3: containerd.runhcs.v1.diag.Save.CompleteSave:output_type -> containerd.runhcs.v1.diag.CompleteSaveResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_init() }
func file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_init() {
	if File_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartSaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartSaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteSaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompleteSaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_goTypes,
		DependencyIndexes: file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_depIdxs,
		MessageInfos:      file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_msgTypes,
	}.Build()
	File_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto = out.File
	file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_rawDesc = nil
	file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_goTypes = nil
	file_dev_azure_com_msazure_ContainerPlatform__git_azcri_git_api_save_save_proto_depIdxs = nil
}
