// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: dev.azure.com/msazure/ContainerPlatform/_git/azcri.git/api/save/save.proto
package save

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)

type SaveService interface {
	StartSave(ctx context.Context, req *StartSaveRequest) (*StartSaveResponse, error)
	CompleteSave(ctx context.Context, req *CompleteSaveRequest) (*CompleteSaveResponse, error)
}

func RegisterSaveService(srv *ttrpc.Server, svc SaveService) {
	srv.Register("containerd.runhcs.v1.diag.Save", map[string]ttrpc.Method{
		"StartSave": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
			var req StartSaveRequest
			if err := unmarshal(&req); err != nil {
				return nil, err
			}
			return svc.StartSave(ctx, &req)
		},
		"CompleteSave": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
			var req CompleteSaveRequest
			if err := unmarshal(&req); err != nil {
				return nil, err
			}
			return svc.CompleteSave(ctx, &req)
		},
	})
}

type saveClient struct {
	client *ttrpc.Client
}

func NewSaveClient(client *ttrpc.Client) SaveService {
	return &saveClient{
		client: client,
	}
}
func (c *saveClient) StartSave(ctx context.Context, req *StartSaveRequest) (*StartSaveResponse, error) {
	var resp StartSaveResponse
	if err := c.client.Call(ctx, "containerd.runhcs.v1.diag.Save", "StartSave", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
func (c *saveClient) CompleteSave(ctx context.Context, req *CompleteSaveRequest) (*CompleteSaveResponse, error) {
	var resp CompleteSaveResponse
	if err := c.client.Call(ctx, "containerd.runhcs.v1.diag.Save", "CompleteSave", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
